name: bs
version: 0.0.1
author: Dieter Hubau <dhubau@gmail.com>
description: Bootstrap Modal polymer element in Dart
homepage: https://github.com/Turbots/bs-modal-dart
documentation: https://github.com/Turbots/bs-modal-dart/blob/master/README.md
dependencies:
    polymer: ">=0.15.1+5 <0.16.0"
    bootstrap: ">=3.3.0+4 <4.0.0"
transformers:
- polymer:
    entry_points:
    - web/index.html
    inline_stylesheets:
      packages/bootstrap/css/bootstrap.min.css: false
