name: bs
version: 0.0.1
author: Dieter Hubau <dhubau@gmail.com>
description: Bootstrap Modal polymer element in Dart
homepage: https://github.com/Turbots/bs-modal-dart
documentation: https://github.com/Turbots/bs-modal-dart/blob/master/README.md
dependencies:
  bootstrap: any
  polymer: any
transformers:
- polymer:
    entry_points:
    - web/index.html
    inline_stylesheets:
      packages/bootstrap/css/bootstrap.min.css: false
